server:
  port: 9991
  contextPath: /auth

security:
  user:
    password: password
  sessions: if-required

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR