server:
  port: 9991
  contextPath: /auth

security:
  user:
    password: password
  sessions: if-required

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

################### Purge cron expression ##########################
#    5am every day
purge:
  cron:
    expression: 0 0 5 * * ?

# Uncomment the keys to enable captcha
google:
    recaptcha:
        key:
            site: 6LfaHiITAAAAAAgZBHl4ZUZAYk5RlOYTr6m2N34X
            secret: 6LfaHiITAAAAANpDTA_Zflwib95IhDqg2SNRLt4U

################### JavaMail Configuration ##########################
support:
  email: eugen@baeldung.com
spring:
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 465
    protocol: smtps
    username: eugen@baeldung.com
    password: 
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 2000
